preprocessor frag3_global: max_frags 65536
preprocessor frag3_engine: policy linux
#tcp stream tracking here
preprocessor stream5_global: track_tcp yes
preprocessor stream5_tcp: policy linux


preprocessor http_inspect: global iis_unicode_map /etc/snort/unicode.map 1252
preprocessor http_inspect_server: server default ports { 8000 }


output alert_fast: stdout

include /etc/snort/rules/local.rules